spring:
  datasource:
    driverClassName:  org.h2.Driver
    username: sa
    password:
    initialize: false
    continueOnError:  true
  jpa:
    database-platform:  org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update